<?xml version="1.0" encoding="utf-8"?><Database Name="CakesPos" Class="CakesPosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=CakesPos;Integrated Security=True" SettingsObjectName="CakesPos.Data.Properties.Settings" SettingsPropertyName="CakesPosConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Category_Product" Member="Products" ThisKey="Id" OtherKey="CategoryId" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetails" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_OrderDetail" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" />
      <Association Name="Order_OrderDetail" Member="Order" ThisKey="OrderId" OtherKey="Id" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payments" Member="Payments">
    <Type Name="Payment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Payment" Member="Payment1" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PaymentNote" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Customer_Payment" Member="Customer" ThisKey="CustomerId" OtherKey="Id" Type="Customer" IsForeignKey="true" />
      <Association Name="Order_Payment" Member="Order" ThisKey="OrderId" OtherKey="Id" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Member="Status1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Order_Status" Member="Order" ThisKey="OrderId" OtherKey="Id" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrdersStatement" Member="OrdersStatements">
    <Type Name="OrdersStatement">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatementId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Statement_OrdersStatement" Member="Statement" ThisKey="StatementId" OtherKey="Id" Type="Statement" IsForeignKey="true" />
      <Association Name="Order_OrdersStatement" Member="Order" ThisKey="OrderId" OtherKey="Id" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Statement" Member="Statements">
    <Type Name="Statement">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="FilePath" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Open]" Member="Open" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Statement_OrdersStatement" Member="OrdersStatements" ThisKey="Id" OtherKey="StatementId" Type="OrdersStatement" />
      <Association Name="Statement_StatementPayment" Member="StatementPayments" ThisKey="Id" OtherKey="StatementId" Type="StatementPayment" />
    </Type>
  </Table>
  <Table Name="dbo.StatementPayments" Member="StatementPayments">
    <Type Name="StatementPayment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StatementId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Payment" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PaymentNote" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Statement_StatementPayment" Member="Statement" ThisKey="StatementId" OtherKey="Id" Type="Statement" IsForeignKey="true" />
      <Association Name="Customer_StatementPayment" Member="Customer" ThisKey="CustomerId" OtherKey="Id" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AccountTrans" Member="AccountTrans">
    <Type Name="AccountTran">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Customer_AccountTran" Member="Customer" ThisKey="CustomerId" OtherKey="Id" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="InStock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RestockAmount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CatererDiscount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Product_OrderDetail" Member="OrderDetails" ThisKey="Id" OtherKey="ProductId" Type="OrderDetail" />
      <Association Name="Category_Product" Member="Category" ThisKey="CategoryId" OtherKey="Id" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cell1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Caterer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Account" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Cell2" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Customer_Payment" Member="Payments" ThisKey="Id" OtherKey="CustomerId" Type="Payment" />
      <Association Name="Customer_StatementPayment" Member="StatementPayments" ThisKey="Id" OtherKey="CustomerId" Type="StatementPayment" />
      <Association Name="Customer_AccountTran" Member="AccountTrans" ThisKey="Id" OtherKey="CustomerId" Type="AccountTran" />
    </Type>
  </Table>
  <Table Name="dbo.Charges" Member="Charges">
    <Type Name="Charge">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_Charge" Member="Order" ThisKey="OrderId" OtherKey="Id" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryOption" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RequiredDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DeliveryFirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryLastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DeliveryCity" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryState" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryZip" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreditCard" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Expiration" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SecurityCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PaymentMethod" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Paid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Greetings" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DeliveryNote" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Invoice" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Statement" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Cell1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cell2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryCharge" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="OrderDetails" ThisKey="Id" OtherKey="OrderId" Type="OrderDetail" />
      <Association Name="Order_Payment" Member="Payments" ThisKey="Id" OtherKey="OrderId" Type="Payment" />
      <Association Name="Order_Status" Member="Status" ThisKey="Id" OtherKey="OrderId" Type="Status" />
      <Association Name="Order_OrdersStatement" Member="OrdersStatements" ThisKey="Id" OtherKey="OrderId" Type="OrdersStatement" />
      <Association Name="Order_Charge" Member="Charges" ThisKey="Id" OtherKey="OrderId" Type="Charge" />
    </Type>
  </Table>
</Database>